CREATE DATABASE DoAn1;
GO

USE DoAn1;
GO

CREATE TABLE LOP (
    MaLop INT PRIMARY KEY IDENTITY(1,1),
    TenLop NVARCHAR(50),
    GVCN NVARCHAR(50)
);

CREATE TABLE SINHVIEN (
    MaSV INT PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(100),
    NgaySinh DATE,
    MaLop INT FOREIGN KEY REFERENCES LOP(MaLop)
);

CREATE TABLE BUOI_HOC (
    MaBuoi INT PRIMARY KEY IDENTITY(1,1),
    MaLop INT FOREIGN KEY REFERENCES LOP(MaLop),
    NgayHoc DATE
);

CREATE TABLE DIEM_DANH (
    MaBuoi INT FOREIGN KEY REFERENCES BUOI_HOC(MaBuoi),
    MaSV INT FOREIGN KEY REFERENCES SINHVIEN(MaSV),
    TrangThai BIT,
    PRIMARY KEY (MaBuoi, MaSV)
);